### ISSUE TITLE
Is this read to go for the Dakota Upgrade ? 

### ISSUE THREAD

**Issue by AltCoiFish** [DeFiCh/defi-btc-anchorer#1]
Just wanted to ask, as I can not test it at the moment, if `dfi-btc-anchorer` is ready to be used after Dakota Upgrade takes place after `block 678,000 `? 

I would like to run it to help the network and possible get some rewards as described in the [Medium-Blogpost](https://defiblockchain.medium.com/dakota-upgrade-further-decentralization-of-defichain-9c1a369fd570)

**Comment by ShengguangXiao** [comment]
@AltCoiFish Yes, you can use `dfi-btc-anchorer` to create anchor after Dakota upgrade. And you can try it on the `testnet` already. 
Here is a wiki to guide you create the anchor. https://github.com/DeFiCh/ain/wiki/Create-Bitcoin-Anchor

**Comment by AltCoiFish** [comment]
Thank you  @ShengguangXiao .
Will close the ticket now due to ticket hygiene.
