### ISSUE TITLE
BTC testnet address as ## Network-wide anchor marker BTC address. Do not change if not sure.

### ISSUE THREAD

**Issue by AltCoiFish** [DeFiCh/defi-btc-anchorer#5]
I am not sure, but in https://github.com/DeFiCh/defi-btc-anchorer/blob/master/config.example.toml#L10 there is still an `btc-testnet` address . Is this correct ?

**Comment by ShengguangXiao** [comment]
This is to finding competeting anchors, you can leave it unchanged.

**Comment by AltCoiFish** [comment]
> This is to finding competeting anchors, you can leave it unchanged.

Thank you, I will not change it. 
But as we switched the the `mainnet` now is there an alternative address we could switch to?

from my last anchor I did see multiple `output addresses` which where used to receive a transaction:

```"output_addresses": [
        "1FtZwEZKknoquUb6DyQHFZ6g6oomXJYEcb",
        "bc1qty9qqqqqqqq9x70gy5mueu0hjszyzgqnfxal28xrc7wa0knjdrusuqn78v",
        "bc1qtklvrnq3u9lkdurg98rdmy8j8t890qsu4grtxcxptqqhegay92qqzul9qm",
        "bc1q9f844cvycm77geqy0vsy4l6n2u2ux4zpyqzhkf9kuftl7xz8vrnq9q2pu7",
        "bc1qq4dckx846mtl4zrs24f5fn88qwxz5ese29hvcp645n0cetancp0sgtsxa9",
        "bc1qpafutjztmmq87xt0rrgjg67zv72vdcpa3dq37xhpvvsfz8law2qsmsluex",
        "bc1qwqdv385u8ny87jzq4cj2gwcxyd69mat5tu9tvw7mj2spv6wr3q2sty7chx",
        "bc1qulu6zpknxlaam96q0lm79wnxuztwsk87msqc5sfqgdh47ywhn8xsregv0e",
        "bc1q0e5hh3km5getalwd4ulgqc0hcqpdtt64xkdms702zhlq9ljts8pqjm6qlw",
        "bc1qzlstvf63en5wrfu6jvrsygywcs2lrmmeg3yssnkla8737s37a5jsv93faf",
        "bc1qnexlucujpz0ygnvncychqqgqqqqqqqqqqqqqqqqqqqqqqqqqqqqq5crz04",
        "bc1q5gnx3nmgdk5ly2p8llwvch6h9yjr3ve2df3yzu"
```
**source:** `curl https://api.smartbit.com.au/v1/blockchain/transaction/557f94aeabb3dfb6ec7f93289a8125bf9c6bfb35c888a3e74522cab4bb7523d7/op-returns | jq`

**Comment by Bushstar** [comment]
That's normal. The anchor data is embedded in those other Bech32 outputs, the very first output is the address held by all DeFi nodes to be able to see the TX on the Bitcoin network.

**Comment by AltCoiFish** [comment]
Thank you for clarifying it. 
But based on https://github.com/DeFiCh/ain/blob/181f9be7864ad9a205ff1383e01b0bf1d059378b/src/chainparams.cpp#L171 would it make sense to change https://github.com/DeFiCh/defi-btc-anchorer/blob/master/config.example.toml#L10 and add the `1FtZwEZKknoquUb6DyQHFZ6g6oomXJYEcb` address ?

**Comment by AltCoiFish** [comment]
So no need to make any changes here?
If so, I can close the issue if no one complaints.
